Fixed main and optimisation
BarabanovaIrina/evolutionary-algorithm pull request #4
Opened 2019-09-12 10:05 UTC by BarabanovaIrina

fixed according to last comments, divided into different files

2019-09-12 16:12 UTC, J3FALL requested changes

2019-09-12 16:12 UTC, J3FALL commented on main.py
> +optimization.write_to_file(**stat_data_of_generation)
Кажется, здесь либо пропущен tab, либо я не совсем понял)
Сейчас получается так, что переменная `stat_data_of_generation` может быть не определена. Если ты хотела записать в файл и визуализировать результаты только последнего запуска, то, думаю, резоннее было эту переменную объявить до цикла.

2019-09-12 16:12 UTC, J3FALL commented on optimization.py
> +    number_of_individuals = 10
Количество индивидов тоже стоит вынести в мета-параметры алгоритма

2019-09-12 16:12 UTC, J3FALL commented on optimization.py
> +    with open('file.txt', 'w') as file:
Путь до файла, куда будет записываться история оптимизации, стоит вынести отдельно в качестве входного параметра у функции `write_to_file`

2019-09-12 16:12 UTC, J3FALL commented on visualization.py
> +    plt.title('Hostory of optimization')
Грамматическая ошибка)
И добавь заодно подписи к осям у графиков.

2019-09-12 16:12 UTC, J3FALL commented on main.py
> +import visualization
В папке с проектом есть 2 скрипта: visualization.py и vizualization.py. С виду, они ничем не отличаются.
Думаю, один из них стоит удалить?

2019-09-12 16:12 UTC, J3FALL commented on visualization.py
> +def get_plot(list_of_mins, list_of_avgs):
Все еще неудачное название у функции

2019-09-13 13:02 UTC, BarabanovaIrina commented on main.py
> +optimization.write_to_file(**stat_data_of_generation)
[fixed](https://github.com/BarabanovaIrina/evolutionary-algorithm/commit/3bc0adbcd9d4bee59c4243988a4c4b480b972254#diff-5bc02cefb3ea9e27f1a6776eabd1935dR15l)

2019-09-13 13:06 UTC, merged